# Generated by Django 4.1.2 on 2022-11-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_alter_lead_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='Category',
            new_name='category',
        ),
    ]
