# Generated by Django 4.1.2 on 2022-11-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_rename_category_lead_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
